on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        run: docker build -t ghcr.io/${{ github.actor }}/hexencoder:latest .

      - name: docker push
        run: docker push ghcr.io/${{ github.repository_owner }}/hexencoder:latest
